//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_Approve
    {
        public string Email { get; set; }
        public int clreqid { get; set; }
        public Nullable<int> logid { get; set; }
        public string proname { get; set; }
        public string prodescription { get; set; }
        public string protype { get; set; }
        public string frontend { get; set; }
        public string backend { get; set; }
        public Nullable<int> duration { get; set; }
        public Nullable<int> rangeamount { get; set; }
        public string senddate { get; set; }
        public Nullable<int> adminapprove { get; set; }
        public Nullable<int> analystapprove { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<bool> complete { get; set; }
        public Nullable<bool> isdeleted { get; set; }
    }
}
