//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class client_reg
    {
        public int regid { get; set; }
        public int logid { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string Sex { get; set; }
        public string DOB { get; set; }
        public int Age { get; set; }
        public int Countryid { get; set; }
        public int Stateid { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Bank { get; set; }
        public string Branch { get; set; }
        public string Password { get; set; }
        public System.DateTime Registraiondate { get; set; }
    }
}
