//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class login_tbl
    {
        public int logid { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<int> usertype { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<bool> isdeleted { get; set; }
    }
}
