//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class softsolutionEntities1 : DbContext
    {
        public softsolutionEntities1()
            : base("name=softsolutionEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<login_tbl> login_tbl { get; set; }
        public DbSet<tbl_emprequest> tbl_emprequest { get; set; }
        public DbSet<tbl_assignmodule> tbl_assignmodule { get; set; }
        public DbSet<tbl_moddivallot> tbl_moddivallot { get; set; }
        public DbSet<Tbl_TLRequest> Tbl_TLRequest { get; set; }
        public DbSet<tbl_anlreq> tbl_anlreq { get; set; }
        public DbSet<project_team> project_team { get; set; }
        public DbSet<Admin_Approve> Admin_Approve { get; set; }
        public DbSet<tbl_module> tbl_module { get; set; }
        public DbSet<tbl_moddiv> tbl_moddiv { get; set; }
        public DbSet<client_reg> client_reg { get; set; }
        public DbSet<tbl_country> tbl_country { get; set; }
        public DbSet<tbl_state> tbl_state { get; set; }
        public DbSet<tbl_analystallot> tbl_analystallot { get; set; }
    
        public virtual ObjectResult<string> sp_employee(string ename, string sex, Nullable<System.DateTime> dOB, Nullable<int> age, string designation)
        {
            var enameParameter = ename != null ?
                new ObjectParameter("Ename", ename) :
                new ObjectParameter("Ename", typeof(string));
    
            var sexParameter = sex != null ?
                new ObjectParameter("Sex", sex) :
                new ObjectParameter("Sex", typeof(string));
    
            var dOBParameter = dOB.HasValue ?
                new ObjectParameter("DOB", dOB) :
                new ObjectParameter("DOB", typeof(System.DateTime));
    
            var ageParameter = age.HasValue ?
                new ObjectParameter("Age", age) :
                new ObjectParameter("Age", typeof(int));
    
            var designationParameter = designation != null ?
                new ObjectParameter("Designation", designation) :
                new ObjectParameter("Designation", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_employee", enameParameter, sexParameter, dOBParameter, ageParameter, designationParameter);
        }
    
        public virtual ObjectResult<string> sp_client_reg(string fname, string lname, string sex, string dOB, Nullable<int> age, Nullable<int> country, Nullable<int> state, string address, string mobile, string email, string password)
        {
            var fnameParameter = fname != null ?
                new ObjectParameter("Fname", fname) :
                new ObjectParameter("Fname", typeof(string));
    
            var lnameParameter = lname != null ?
                new ObjectParameter("Lname", lname) :
                new ObjectParameter("Lname", typeof(string));
    
            var sexParameter = sex != null ?
                new ObjectParameter("Sex", sex) :
                new ObjectParameter("Sex", typeof(string));
    
            var dOBParameter = dOB != null ?
                new ObjectParameter("DOB", dOB) :
                new ObjectParameter("DOB", typeof(string));
    
            var ageParameter = age.HasValue ?
                new ObjectParameter("Age", age) :
                new ObjectParameter("Age", typeof(int));
    
            var countryParameter = country.HasValue ?
                new ObjectParameter("country", country) :
                new ObjectParameter("country", typeof(int));
    
            var stateParameter = state.HasValue ?
                new ObjectParameter("State", state) :
                new ObjectParameter("State", typeof(int));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var mobileParameter = mobile != null ?
                new ObjectParameter("Mobile", mobile) :
                new ObjectParameter("Mobile", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_client_reg", fnameParameter, lnameParameter, sexParameter, dOBParameter, ageParameter, countryParameter, stateParameter, addressParameter, mobileParameter, emailParameter, passwordParameter);
        }
    
        public virtual int sp_cancel(Nullable<int> proid)
        {
            var proidParameter = proid.HasValue ?
                new ObjectParameter("proid", proid) :
                new ObjectParameter("proid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_cancel", proidParameter);
        }
    
        public virtual ObjectResult<string> sp_analystreg(string email, string password)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_analystreg", emailParameter, passwordParameter);
        }
    
        public virtual ObjectResult<string> sp_analystallot(Nullable<int> analystid, Nullable<int> projid)
        {
            var analystidParameter = analystid.HasValue ?
                new ObjectParameter("analystid", analystid) :
                new ObjectParameter("analystid", typeof(int));
    
            var projidParameter = projid.HasValue ?
                new ObjectParameter("projid", projid) :
                new ObjectParameter("projid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_analystallot", analystidParameter, projidParameter);
        }
    
        public virtual ObjectResult<sp_vw_moddiv_id_Result> sp_vw_moddiv_id(Nullable<int> moddivid)
        {
            var moddividParameter = moddivid.HasValue ?
                new ObjectParameter("moddivid", moddivid) :
                new ObjectParameter("moddivid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vw_moddiv_id_Result>("sp_vw_moddiv_id", moddividParameter);
        }
    
        public virtual ObjectResult<sp_vw_emp_team_Result> sp_vw_emp_team(Nullable<int> leadid)
        {
            var leadidParameter = leadid.HasValue ?
                new ObjectParameter("leadid", leadid) :
                new ObjectParameter("leadid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vw_emp_team_Result>("sp_vw_emp_team", leadidParameter);
        }
    
        public virtual ObjectResult<string> sp_division_allot(Nullable<int> divid, Nullable<int> empid, string startdate, string enddate)
        {
            var dividParameter = divid.HasValue ?
                new ObjectParameter("divid", divid) :
                new ObjectParameter("divid", typeof(int));
    
            var empidParameter = empid.HasValue ?
                new ObjectParameter("empid", empid) :
                new ObjectParameter("empid", typeof(int));
    
            var startdateParameter = startdate != null ?
                new ObjectParameter("startdate", startdate) :
                new ObjectParameter("startdate", typeof(string));
    
            var enddateParameter = enddate != null ?
                new ObjectParameter("enddate", enddate) :
                new ObjectParameter("enddate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_division_allot", dividParameter, empidParameter, startdateParameter, enddateParameter);
        }
    
        public virtual ObjectResult<string> sp_check_allot(Nullable<int> empid)
        {
            var empidParameter = empid.HasValue ?
                new ObjectParameter("empid", empid) :
                new ObjectParameter("empid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_check_allot", empidParameter);
        }
    
        public virtual ObjectResult<sp_vw_tlrequest_Result> sp_vw_tlrequest(Nullable<int> anid)
        {
            var anidParameter = anid.HasValue ?
                new ObjectParameter("anid", anid) :
                new ObjectParameter("anid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vw_tlrequest_Result>("sp_vw_tlrequest", anidParameter);
        }
    
        public virtual ObjectResult<string> sp_create_division(Nullable<int> moduleid, string diname, string desc, string document)
        {
            var moduleidParameter = moduleid.HasValue ?
                new ObjectParameter("moduleid", moduleid) :
                new ObjectParameter("moduleid", typeof(int));
    
            var dinameParameter = diname != null ?
                new ObjectParameter("diname", diname) :
                new ObjectParameter("diname", typeof(string));
    
            var descParameter = desc != null ?
                new ObjectParameter("desc", desc) :
                new ObjectParameter("desc", typeof(string));
    
            var documentParameter = document != null ?
                new ObjectParameter("document", document) :
                new ObjectParameter("document", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_create_division", moduleidParameter, dinameParameter, descParameter, documentParameter);
        }
    
        public virtual ObjectResult<string> sp_TLRequest(Nullable<int> lid, Nullable<int> modid, Nullable<int> days, string reason, string enddate)
        {
            var lidParameter = lid.HasValue ?
                new ObjectParameter("lid", lid) :
                new ObjectParameter("lid", typeof(int));
    
            var modidParameter = modid.HasValue ?
                new ObjectParameter("modid", modid) :
                new ObjectParameter("modid", typeof(int));
    
            var daysParameter = days.HasValue ?
                new ObjectParameter("days", days) :
                new ObjectParameter("days", typeof(int));
    
            var reasonParameter = reason != null ?
                new ObjectParameter("reason", reason) :
                new ObjectParameter("reason", typeof(string));
    
            var enddateParameter = enddate != null ?
                new ObjectParameter("enddate", enddate) :
                new ObjectParameter("enddate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_TLRequest", lidParameter, modidParameter, daysParameter, reasonParameter, enddateParameter);
        }
    
        public virtual ObjectResult<string> sp_addanalyst(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_addanalyst", usernameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<string> sp_addprjleader(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_addprjleader", usernameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<string> sp_addteam(Nullable<int> leaderid, string teamname)
        {
            var leaderidParameter = leaderid.HasValue ?
                new ObjectParameter("leaderid", leaderid) :
                new ObjectParameter("leaderid", typeof(int));
    
            var teamnameParameter = teamname != null ?
                new ObjectParameter("teamname", teamname) :
                new ObjectParameter("teamname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_addteam", leaderidParameter, teamnameParameter);
        }
    
        public virtual ObjectResult<string> sp_split_prj_module(Nullable<int> prjid, string modulename, string desc, string doc)
        {
            var prjidParameter = prjid.HasValue ?
                new ObjectParameter("prjid", prjid) :
                new ObjectParameter("prjid", typeof(int));
    
            var modulenameParameter = modulename != null ?
                new ObjectParameter("modulename", modulename) :
                new ObjectParameter("modulename", typeof(string));
    
            var descParameter = desc != null ?
                new ObjectParameter("desc", desc) :
                new ObjectParameter("desc", typeof(string));
    
            var docParameter = doc != null ?
                new ObjectParameter("doc", doc) :
                new ObjectParameter("doc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_split_prj_module", prjidParameter, modulenameParameter, descParameter, docParameter);
        }
    
        public virtual ObjectResult<sp_vw_moddiv_Result> sp_vw_moddiv(Nullable<int> logid)
        {
            var logidParameter = logid.HasValue ?
                new ObjectParameter("logid", logid) :
                new ObjectParameter("logid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vw_moddiv_Result>("sp_vw_moddiv", logidParameter);
        }
    
        public virtual ObjectResult<string> sp_employee_requests(Nullable<int> divid, Nullable<int> logid, string reason, Nullable<int> daysneeded, string enddate)
        {
            var dividParameter = divid.HasValue ?
                new ObjectParameter("divid", divid) :
                new ObjectParameter("divid", typeof(int));
    
            var logidParameter = logid.HasValue ?
                new ObjectParameter("logid", logid) :
                new ObjectParameter("logid", typeof(int));
    
            var reasonParameter = reason != null ?
                new ObjectParameter("reason", reason) :
                new ObjectParameter("reason", typeof(string));
    
            var daysneededParameter = daysneeded.HasValue ?
                new ObjectParameter("daysneeded", daysneeded) :
                new ObjectParameter("daysneeded", typeof(int));
    
            var enddateParameter = enddate != null ?
                new ObjectParameter("enddate", enddate) :
                new ObjectParameter("enddate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_employee_requests", dividParameter, logidParameter, reasonParameter, daysneededParameter, enddateParameter);
        }
    
        public virtual ObjectResult<string> sp_employee_submit(Nullable<int> divid, Nullable<int> logid, string document)
        {
            var dividParameter = divid.HasValue ?
                new ObjectParameter("divid", divid) :
                new ObjectParameter("divid", typeof(int));
    
            var logidParameter = logid.HasValue ?
                new ObjectParameter("logid", logid) :
                new ObjectParameter("logid", typeof(int));
    
            var documentParameter = document != null ?
                new ObjectParameter("document", document) :
                new ObjectParameter("document", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_employee_submit", dividParameter, logidParameter, documentParameter);
        }
    
        public virtual ObjectResult<sp_vw_emp_request_Result> sp_vw_emp_request(Nullable<int> tlid)
        {
            var tlidParameter = tlid.HasValue ?
                new ObjectParameter("tlid", tlid) :
                new ObjectParameter("tlid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vw_emp_request_Result>("sp_vw_emp_request", tlidParameter);
        }
    
        public virtual ObjectResult<string> spTlResponseRequest(Nullable<int> empreqid, Nullable<int> days, string edate)
        {
            var empreqidParameter = empreqid.HasValue ?
                new ObjectParameter("empreqid", empreqid) :
                new ObjectParameter("empreqid", typeof(int));
    
            var daysParameter = days.HasValue ?
                new ObjectParameter("days", days) :
                new ObjectParameter("days", typeof(int));
    
            var edateParameter = edate != null ?
                new ObjectParameter("edate", edate) :
                new ObjectParameter("edate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("spTlResponseRequest", empreqidParameter, daysParameter, edateParameter);
        }
    
        public virtual ObjectResult<spempvwempcomplete_Result> spempvwempcomplete(Nullable<int> tlid)
        {
            var tlidParameter = tlid.HasValue ?
                new ObjectParameter("tlid", tlid) :
                new ObjectParameter("tlid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spempvwempcomplete_Result>("spempvwempcomplete", tlidParameter);
        }
    
        public virtual ObjectResult<string> spTlsubmit(Nullable<int> tlid, string documents)
        {
            var tlidParameter = tlid.HasValue ?
                new ObjectParameter("tlid", tlid) :
                new ObjectParameter("tlid", typeof(int));
    
            var documentsParameter = documents != null ?
                new ObjectParameter("documents", documents) :
                new ObjectParameter("documents", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("spTlsubmit", tlidParameter, documentsParameter);
        }
    
        public virtual ObjectResult<string> sp_AnalystRequest(Nullable<int> lid, Nullable<int> prjid, Nullable<int> days, string reason, string enddate)
        {
            var lidParameter = lid.HasValue ?
                new ObjectParameter("lid", lid) :
                new ObjectParameter("lid", typeof(int));
    
            var prjidParameter = prjid.HasValue ?
                new ObjectParameter("prjid", prjid) :
                new ObjectParameter("prjid", typeof(int));
    
            var daysParameter = days.HasValue ?
                new ObjectParameter("days", days) :
                new ObjectParameter("days", typeof(int));
    
            var reasonParameter = reason != null ?
                new ObjectParameter("reason", reason) :
                new ObjectParameter("reason", typeof(string));
    
            var enddateParameter = enddate != null ?
                new ObjectParameter("enddate", enddate) :
                new ObjectParameter("enddate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_AnalystRequest", lidParameter, prjidParameter, daysParameter, reasonParameter, enddateParameter);
        }
    
        public virtual ObjectResult<spvw_tlmodulecomplete_Result> spvw_tlmodulecomplete(Nullable<int> lid)
        {
            var lidParameter = lid.HasValue ?
                new ObjectParameter("lid", lid) :
                new ObjectParameter("lid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spvw_tlmodulecomplete_Result>("spvw_tlmodulecomplete", lidParameter);
        }
    
        public virtual ObjectResult<string> sp_analystsubmit(Nullable<int> anid, Nullable<int> prjid, string remark, string document)
        {
            var anidParameter = anid.HasValue ?
                new ObjectParameter("anid", anid) :
                new ObjectParameter("anid", typeof(int));
    
            var prjidParameter = prjid.HasValue ?
                new ObjectParameter("prjid", prjid) :
                new ObjectParameter("prjid", typeof(int));
    
            var remarkParameter = remark != null ?
                new ObjectParameter("remark", remark) :
                new ObjectParameter("remark", typeof(string));
    
            var documentParameter = document != null ?
                new ObjectParameter("document", document) :
                new ObjectParameter("document", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_analystsubmit", anidParameter, prjidParameter, remarkParameter, documentParameter);
        }
    
        public virtual ObjectResult<sp_vw_tl_request_Result> sp_vw_tl_request(Nullable<int> anlid)
        {
            var anlidParameter = anlid.HasValue ?
                new ObjectParameter("anlid", anlid) :
                new ObjectParameter("anlid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vw_tl_request_Result>("sp_vw_tl_request", anlidParameter);
        }
    
        public virtual ObjectResult<string> spAnalystResponseRequest(Nullable<int> tlreqid, Nullable<int> days, string edate)
        {
            var tlreqidParameter = tlreqid.HasValue ?
                new ObjectParameter("tlreqid", tlreqid) :
                new ObjectParameter("tlreqid", typeof(int));
    
            var daysParameter = days.HasValue ?
                new ObjectParameter("days", days) :
                new ObjectParameter("days", typeof(int));
    
            var edateParameter = edate != null ?
                new ObjectParameter("edate", edate) :
                new ObjectParameter("edate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("spAnalystResponseRequest", tlreqidParameter, daysParameter, edateParameter);
        }
    
        public virtual ObjectResult<sp_vw_analyst_request_Result> sp_vw_analyst_request()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vw_analyst_request_Result>("sp_vw_analyst_request");
        }
    
        public virtual ObjectResult<string> spAdminResponseRequest(Nullable<int> anlreqid, Nullable<int> days, string edate)
        {
            var anlreqidParameter = anlreqid.HasValue ?
                new ObjectParameter("anlreqid", anlreqid) :
                new ObjectParameter("anlreqid", typeof(int));
    
            var daysParameter = days.HasValue ?
                new ObjectParameter("days", days) :
                new ObjectParameter("days", typeof(int));
    
            var edateParameter = edate != null ?
                new ObjectParameter("edate", edate) :
                new ObjectParameter("edate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("spAdminResponseRequest", anlreqidParameter, daysParameter, edateParameter);
        }
    
        public virtual ObjectResult<sp_vw_TeamLeader_Result> sp_vw_TeamLeader()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vw_TeamLeader_Result>("sp_vw_TeamLeader");
        }
    
        public virtual ObjectResult<string> sp_client(string email, string description, string type, string frontend, string backend, string date, Nullable<int> logid, string proname)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            var frontendParameter = frontend != null ?
                new ObjectParameter("Frontend", frontend) :
                new ObjectParameter("Frontend", typeof(string));
    
            var backendParameter = backend != null ?
                new ObjectParameter("Backend", backend) :
                new ObjectParameter("Backend", typeof(string));
    
            var dateParameter = date != null ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(string));
    
            var logidParameter = logid.HasValue ?
                new ObjectParameter("logid", logid) :
                new ObjectParameter("logid", typeof(int));
    
            var pronameParameter = proname != null ?
                new ObjectParameter("proname", proname) :
                new ObjectParameter("proname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_client", emailParameter, descriptionParameter, typeParameter, frontendParameter, backendParameter, dateParameter, logidParameter, pronameParameter);
        }
    
        public virtual ObjectResult<string> sp_Approve(Nullable<int> proid, string startdate, string enddate, Nullable<int> analystid)
        {
            var proidParameter = proid.HasValue ?
                new ObjectParameter("proid", proid) :
                new ObjectParameter("proid", typeof(int));
    
            var startdateParameter = startdate != null ?
                new ObjectParameter("startdate", startdate) :
                new ObjectParameter("startdate", typeof(string));
    
            var enddateParameter = enddate != null ?
                new ObjectParameter("enddate", enddate) :
                new ObjectParameter("enddate", typeof(string));
    
            var analystidParameter = analystid.HasValue ?
                new ObjectParameter("analystid", analystid) :
                new ObjectParameter("analystid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_Approve", proidParameter, startdateParameter, enddateParameter, analystidParameter);
        }
    
        public virtual ObjectResult<string> sp_addemployee(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_addemployee", usernameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<string> sp_addanalyst_work_status(Nullable<int> prjid, Nullable<double> per, Nullable<int> duration)
        {
            var prjidParameter = prjid.HasValue ?
                new ObjectParameter("prjid", prjid) :
                new ObjectParameter("prjid", typeof(int));
    
            var perParameter = per.HasValue ?
                new ObjectParameter("per", per) :
                new ObjectParameter("per", typeof(double));
    
            var durationParameter = duration.HasValue ?
                new ObjectParameter("duration", duration) :
                new ObjectParameter("duration", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_addanalyst_work_status", prjidParameter, perParameter, durationParameter);
        }
    
        public virtual ObjectResult<string> sp_addEmp_work_status(Nullable<int> divid, Nullable<double> per, Nullable<int> duration)
        {
            var dividParameter = divid.HasValue ?
                new ObjectParameter("divid", divid) :
                new ObjectParameter("divid", typeof(int));
    
            var perParameter = per.HasValue ?
                new ObjectParameter("per", per) :
                new ObjectParameter("per", typeof(double));
    
            var durationParameter = duration.HasValue ?
                new ObjectParameter("duration", duration) :
                new ObjectParameter("duration", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_addEmp_work_status", dividParameter, perParameter, durationParameter);
        }
    
        public virtual ObjectResult<string> sp_addTL_work_status(Nullable<int> modid, Nullable<double> per, Nullable<int> duration)
        {
            var modidParameter = modid.HasValue ?
                new ObjectParameter("modid", modid) :
                new ObjectParameter("modid", typeof(int));
    
            var perParameter = per.HasValue ?
                new ObjectParameter("per", per) :
                new ObjectParameter("per", typeof(double));
    
            var durationParameter = duration.HasValue ?
                new ObjectParameter("duration", duration) :
                new ObjectParameter("duration", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_addTL_work_status", modidParameter, perParameter, durationParameter);
        }
    
        public virtual ObjectResult<sp_vw_division_empid_Result> sp_vw_division_empid(Nullable<int> logid)
        {
            var logidParameter = logid.HasValue ?
                new ObjectParameter("logid", logid) :
                new ObjectParameter("logid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vw_division_empid_Result>("sp_vw_division_empid", logidParameter);
        }
    
        public virtual ObjectResult<spvwprevstatus_employee_Result> spvwprevstatus_employee(Nullable<int> moddivid)
        {
            var moddividParameter = moddivid.HasValue ?
                new ObjectParameter("moddivid", moddivid) :
                new ObjectParameter("moddivid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spvwprevstatus_employee_Result>("spvwprevstatus_employee", moddividParameter);
        }
    
        public virtual ObjectResult<spvwstatus_tl_Result> spvwstatus_tl(Nullable<int> tlid)
        {
            var tlidParameter = tlid.HasValue ?
                new ObjectParameter("tlid", tlid) :
                new ObjectParameter("tlid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spvwstatus_tl_Result>("spvwstatus_tl", tlidParameter);
        }
    
        public virtual ObjectResult<spvw_moduletl_Result> spvw_moduletl(Nullable<int> logid)
        {
            var logidParameter = logid.HasValue ?
                new ObjectParameter("logid", logid) :
                new ObjectParameter("logid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spvw_moduletl_Result>("spvw_moduletl", logidParameter);
        }
    
        public virtual ObjectResult<string> sp_modulestatus_tl(Nullable<int> modid, Nullable<double> percent, Nullable<int> duration)
        {
            var modidParameter = modid.HasValue ?
                new ObjectParameter("modid", modid) :
                new ObjectParameter("modid", typeof(int));
    
            var percentParameter = percent.HasValue ?
                new ObjectParameter("percent", percent) :
                new ObjectParameter("percent", typeof(double));
    
            var durationParameter = duration.HasValue ?
                new ObjectParameter("duration", duration) :
                new ObjectParameter("duration", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_modulestatus_tl", modidParameter, percentParameter, durationParameter);
        }
    
        public virtual ObjectResult<sp_vw_prjid_analyst_Result> sp_vw_prjid_analyst(Nullable<int> logid)
        {
            var logidParameter = logid.HasValue ?
                new ObjectParameter("logid", logid) :
                new ObjectParameter("logid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vw_prjid_analyst_Result>("sp_vw_prjid_analyst", logidParameter);
        }
    
        public virtual ObjectResult<string> sp_projectstatus_analyst(Nullable<int> prjid, Nullable<double> percent, Nullable<int> duration)
        {
            var prjidParameter = prjid.HasValue ?
                new ObjectParameter("prjid", prjid) :
                new ObjectParameter("prjid", typeof(int));
    
            var percentParameter = percent.HasValue ?
                new ObjectParameter("percent", percent) :
                new ObjectParameter("percent", typeof(double));
    
            var durationParameter = duration.HasValue ?
                new ObjectParameter("duration", duration) :
                new ObjectParameter("duration", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_projectstatus_analyst", prjidParameter, percentParameter, durationParameter);
        }
    
        public virtual int SpChat(Nullable<int> priid, Nullable<int> fromid, string message)
        {
            var priidParameter = priid.HasValue ?
                new ObjectParameter("priid", priid) :
                new ObjectParameter("priid", typeof(int));
    
            var fromidParameter = fromid.HasValue ?
                new ObjectParameter("fromid", fromid) :
                new ObjectParameter("fromid", typeof(int));
    
            var messageParameter = message != null ?
                new ObjectParameter("message", message) :
                new ObjectParameter("message", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SpChat", priidParameter, fromidParameter, messageParameter);
        }
    
        public virtual ObjectResult<string> spaddprjstatus(Nullable<int> prjid, Nullable<double> per, Nullable<int> exp)
        {
            var prjidParameter = prjid.HasValue ?
                new ObjectParameter("prjid", prjid) :
                new ObjectParameter("prjid", typeof(int));
    
            var perParameter = per.HasValue ?
                new ObjectParameter("per", per) :
                new ObjectParameter("per", typeof(double));
    
            var expParameter = exp.HasValue ?
                new ObjectParameter("exp", exp) :
                new ObjectParameter("exp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("spaddprjstatus", prjidParameter, perParameter, expParameter);
        }
    
        public virtual ObjectResult<spvwstatus_Analyst_Result> spvwstatus_Analyst(Nullable<int> analystid)
        {
            var analystidParameter = analystid.HasValue ?
                new ObjectParameter("analystid", analystid) :
                new ObjectParameter("analystid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spvwstatus_Analyst_Result>("spvwstatus_Analyst", analystidParameter);
        }
    
        public virtual ObjectResult<spanalystchartdetails_Result> spanalystchartdetails(Nullable<int> analystid, Nullable<int> prjid)
        {
            var analystidParameter = analystid.HasValue ?
                new ObjectParameter("analystid", analystid) :
                new ObjectParameter("analystid", typeof(int));
    
            var prjidParameter = prjid.HasValue ?
                new ObjectParameter("prjid", prjid) :
                new ObjectParameter("prjid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spanalystchartdetails_Result>("spanalystchartdetails", analystidParameter, prjidParameter);
        }
    
        public virtual ObjectResult<sp_client_view_Result> sp_client_view()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_client_view_Result>("sp_client_view");
        }
    
        public virtual ObjectResult<sp_view_analyst_projects_Result> sp_view_analyst_projects(Nullable<int> logid)
        {
            var logidParameter = logid.HasValue ?
                new ObjectParameter("logid", logid) :
                new ObjectParameter("logid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_view_analyst_projects_Result>("sp_view_analyst_projects", logidParameter);
        }
    
        public virtual ObjectResult<sp_vw_cust_prjdetails_Result> sp_vw_cust_prjdetails(Nullable<int> logid)
        {
            var logidParameter = logid.HasValue ?
                new ObjectParameter("logid", logid) :
                new ObjectParameter("logid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vw_cust_prjdetails_Result>("sp_vw_cust_prjdetails", logidParameter);
        }
    
        public virtual ObjectResult<spvw_prjallot_Result> spvw_prjallot(Nullable<int> alogid)
        {
            var alogidParameter = alogid.HasValue ?
                new ObjectParameter("alogid", alogid) :
                new ObjectParameter("alogid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spvw_prjallot_Result>("spvw_prjallot", alogidParameter);
        }
    
        public virtual ObjectResult<sp_vw_emp_Result> sp_vw_emp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vw_emp_Result>("sp_vw_emp");
        }
    
        public virtual ObjectResult<sp_vw_division_id_Result> sp_vw_division_id(Nullable<int> modid)
        {
            var modidParameter = modid.HasValue ?
                new ObjectParameter("modid", modid) :
                new ObjectParameter("modid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vw_division_id_Result>("sp_vw_division_id", modidParameter);
        }
    
        public virtual ObjectResult<sp_vw_emp_team_status_Result> sp_vw_emp_team_status(Nullable<int> leadid)
        {
            var leadidParameter = leadid.HasValue ?
                new ObjectParameter("leadid", leadid) :
                new ObjectParameter("leadid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vw_emp_team_status_Result>("sp_vw_emp_team_status", leadidParameter);
        }
    
        public virtual ObjectResult<sp_vw_division_id_staus_Result> sp_vw_division_id_staus(Nullable<int> modid)
        {
            var modidParameter = modid.HasValue ?
                new ObjectParameter("modid", modid) :
                new ObjectParameter("modid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vw_division_id_staus_Result>("sp_vw_division_id_staus", modidParameter);
        }
    
        public virtual int sp_split_complete(Nullable<int> modid)
        {
            var modidParameter = modid.HasValue ?
                new ObjectParameter("modid", modid) :
                new ObjectParameter("modid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_split_complete", modidParameter);
        }
    
        public virtual ObjectResult<sp_vw_divisionname_Result> sp_vw_divisionname(Nullable<int> modid)
        {
            var modidParameter = modid.HasValue ?
                new ObjectParameter("modid", modid) :
                new ObjectParameter("modid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vw_divisionname_Result>("sp_vw_divisionname", modidParameter);
        }
    
        public virtual ObjectResult<sp_vw_moddiv_emp_Result> sp_vw_moddiv_emp(Nullable<int> logid)
        {
            var logidParameter = logid.HasValue ?
                new ObjectParameter("logid", logid) :
                new ObjectParameter("logid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vw_moddiv_emp_Result>("sp_vw_moddiv_emp", logidParameter);
        }
    
        public virtual ObjectResult<spvwstatus_Employee_Result> spvwstatus_Employee(Nullable<int> logid)
        {
            var logidParameter = logid.HasValue ?
                new ObjectParameter("logid", logid) :
                new ObjectParameter("logid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spvwstatus_Employee_Result>("spvwstatus_Employee", logidParameter);
        }
    
        public virtual ObjectResult<spvwstatus_Analyst_chart_Result> spvwstatus_Analyst_chart(Nullable<int> analystid)
        {
            var analystidParameter = analystid.HasValue ?
                new ObjectParameter("analystid", analystid) :
                new ObjectParameter("analystid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spvwstatus_Analyst_chart_Result>("spvwstatus_Analyst_chart", analystidParameter);
        }
    
        public virtual ObjectResult<sp_project_status_admin_Result> sp_project_status_admin()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_project_status_admin_Result>("sp_project_status_admin");
        }
    
        public virtual ObjectResult<sp_vw_cust_msg_Result> sp_vw_cust_msg(Nullable<int> logid, Nullable<int> prjid)
        {
            var logidParameter = logid.HasValue ?
                new ObjectParameter("logid", logid) :
                new ObjectParameter("logid", typeof(int));
    
            var prjidParameter = prjid.HasValue ?
                new ObjectParameter("prjid", prjid) :
                new ObjectParameter("prjid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vw_cust_msg_Result>("sp_vw_cust_msg", logidParameter, prjidParameter);
        }
    
        public virtual ObjectResult<sp_vw_msg_analyst_Result> sp_vw_msg_analyst(Nullable<int> analystid)
        {
            var analystidParameter = analystid.HasValue ?
                new ObjectParameter("analystid", analystid) :
                new ObjectParameter("analystid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vw_msg_analyst_Result>("sp_vw_msg_analyst", analystidParameter);
        }
    
        public virtual ObjectResult<SpChatView_Result> SpChatView(Nullable<int> priid)
        {
            var priidParameter = priid.HasValue ?
                new ObjectParameter("priid", priid) :
                new ObjectParameter("priid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpChatView_Result>("SpChatView", priidParameter);
        }
    
        public virtual ObjectResult<string> sp_assign_employee(Nullable<int> leaderid, Nullable<int> logid, string designation)
        {
            var leaderidParameter = leaderid.HasValue ?
                new ObjectParameter("leaderid", leaderid) :
                new ObjectParameter("leaderid", typeof(int));
    
            var logidParameter = logid.HasValue ?
                new ObjectParameter("logid", logid) :
                new ObjectParameter("logid", typeof(int));
    
            var designationParameter = designation != null ?
                new ObjectParameter("designation", designation) :
                new ObjectParameter("designation", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_assign_employee", leaderidParameter, logidParameter, designationParameter);
        }
    
        public virtual ObjectResult<sp_vw_module_id_Result> sp_vw_module_id(Nullable<int> modid)
        {
            var modidParameter = modid.HasValue ?
                new ObjectParameter("modid", modid) :
                new ObjectParameter("modid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vw_module_id_Result>("sp_vw_module_id", modidParameter);
        }
    
        public virtual ObjectResult<sp_vw_cust_chart_Result> sp_vw_cust_chart(Nullable<int> logid)
        {
            var logidParameter = logid.HasValue ?
                new ObjectParameter("logid", logid) :
                new ObjectParameter("logid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vw_cust_chart_Result>("sp_vw_cust_chart", logidParameter);
        }
    
        public virtual ObjectResult<sp_vw_project_analysst_Result> sp_vw_project_analysst(Nullable<int> anlid)
        {
            var anlidParameter = anlid.HasValue ?
                new ObjectParameter("anlid", anlid) :
                new ObjectParameter("anlid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vw_project_analysst_Result>("sp_vw_project_analysst", anlidParameter);
        }
    
        public virtual ObjectResult<string> sp_updateclient_profile(Nullable<int> logid, string fname, string lname, string dob, Nullable<int> country, Nullable<int> state, string address, string mobile, string email)
        {
            var logidParameter = logid.HasValue ?
                new ObjectParameter("logid", logid) :
                new ObjectParameter("logid", typeof(int));
    
            var fnameParameter = fname != null ?
                new ObjectParameter("fname", fname) :
                new ObjectParameter("fname", typeof(string));
    
            var lnameParameter = lname != null ?
                new ObjectParameter("lname", lname) :
                new ObjectParameter("lname", typeof(string));
    
            var dobParameter = dob != null ?
                new ObjectParameter("dob", dob) :
                new ObjectParameter("dob", typeof(string));
    
            var countryParameter = country.HasValue ?
                new ObjectParameter("country", country) :
                new ObjectParameter("country", typeof(int));
    
            var stateParameter = state.HasValue ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(int));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var mobileParameter = mobile != null ?
                new ObjectParameter("mobile", mobile) :
                new ObjectParameter("mobile", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_updateclient_profile", logidParameter, fnameParameter, lnameParameter, dobParameter, countryParameter, stateParameter, addressParameter, mobileParameter, emailParameter);
        }
    
        public virtual ObjectResult<sp_view_chat> sp_view_chat(Nullable<int> logid)
        {
            var logidParameter = logid.HasValue ?
                new ObjectParameter("logid", logid) :
                new ObjectParameter("logid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_view_chat>("sp_view_chat", logidParameter);
        }
    
        public virtual ObjectResult<sp_view_thread> sp_view_thread(Nullable<int> from, Nullable<int> to)
        {
            var fromParameter = from.HasValue ?
                new ObjectParameter("from", from) :
                new ObjectParameter("from", typeof(int));
    
            var toParameter = to.HasValue ?
                new ObjectParameter("to", to) :
                new ObjectParameter("to", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_view_thread>("sp_view_thread", fromParameter, toParameter);
        }
    
        public virtual ObjectResult<string> sp_msg_delete(Nullable<int> msg_id, Nullable<int> log_id)
        {
            var msg_idParameter = msg_id.HasValue ?
                new ObjectParameter("msg_id", msg_id) :
                new ObjectParameter("msg_id", typeof(int));
    
            var log_idParameter = log_id.HasValue ?
                new ObjectParameter("log_id", log_id) :
                new ObjectParameter("log_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_msg_delete", msg_idParameter, log_idParameter);
        }
    
        public virtual ObjectResult<sp_view_thread_bind> sp_view_thread_bind(Nullable<int> from, Nullable<int> to)
        {
            var fromParameter = from.HasValue ?
                new ObjectParameter("from", from) :
                new ObjectParameter("from", typeof(int));
    
            var toParameter = to.HasValue ?
                new ObjectParameter("to", to) :
                new ObjectParameter("to", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_view_thread_bind>("sp_view_thread_bind", fromParameter, toParameter);
        }
    
        public virtual ObjectResult<string> sp_msg_delete_all(Nullable<int> log_id, Nullable<int> profile_id)
        {
            var log_idParameter = log_id.HasValue ?
                new ObjectParameter("log_id", log_id) :
                new ObjectParameter("log_id", typeof(int));
    
            var profile_idParameter = profile_id.HasValue ?
                new ObjectParameter("profile_id", profile_id) :
                new ObjectParameter("profile_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_msg_delete_all", log_idParameter, profile_idParameter);
        }
    
        public virtual ObjectResult<string> sp_message(Nullable<int> from, Nullable<int> to, string message)
        {
            var fromParameter = from.HasValue ?
                new ObjectParameter("from", from) :
                new ObjectParameter("from", typeof(int));
    
            var toParameter = to.HasValue ?
                new ObjectParameter("to", to) :
                new ObjectParameter("to", typeof(int));
    
            var messageParameter = message != null ?
                new ObjectParameter("message", message) :
                new ObjectParameter("message", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_message", fromParameter, toParameter, messageParameter);
        }
    
        public virtual ObjectResult<sp_vw_analystid_Result> sp_vw_analystid(Nullable<int> clreqid)
        {
            var clreqidParameter = clreqid.HasValue ?
                new ObjectParameter("clreqid", clreqid) :
                new ObjectParameter("clreqid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vw_analystid_Result>("sp_vw_analystid", clreqidParameter);
        }
    
        public virtual ObjectResult<sp_clientprofile_Result> sp_clientprofile(Nullable<int> logid)
        {
            var logidParameter = logid.HasValue ?
                new ObjectParameter("logid", logid) :
                new ObjectParameter("logid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_clientprofile_Result>("sp_clientprofile", logidParameter);
        }
    
        public virtual ObjectResult<spvwmodule_assign_prj_Result> spvwmodule_assign_prj(Nullable<int> prjid)
        {
            var prjidParameter = prjid.HasValue ?
                new ObjectParameter("prjid", prjid) :
                new ObjectParameter("prjid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spvwmodule_assign_prj_Result>("spvwmodule_assign_prj", prjidParameter);
        }
    
        public virtual ObjectResult<spvwmodule_prj_Result> spvwmodule_prj(Nullable<int> prjid)
        {
            var prjidParameter = prjid.HasValue ?
                new ObjectParameter("prjid", prjid) :
                new ObjectParameter("prjid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spvwmodule_prj_Result>("spvwmodule_prj", prjidParameter);
        }
    
        public virtual ObjectResult<string> sp_assignmodule(Nullable<int> modid, Nullable<int> teamid, string startdate, Nullable<int> prjid, string enddate)
        {
            var modidParameter = modid.HasValue ?
                new ObjectParameter("modid", modid) :
                new ObjectParameter("modid", typeof(int));
    
            var teamidParameter = teamid.HasValue ?
                new ObjectParameter("teamid", teamid) :
                new ObjectParameter("teamid", typeof(int));
    
            var startdateParameter = startdate != null ?
                new ObjectParameter("startdate", startdate) :
                new ObjectParameter("startdate", typeof(string));
    
            var prjidParameter = prjid.HasValue ?
                new ObjectParameter("prjid", prjid) :
                new ObjectParameter("prjid", typeof(int));
    
            var enddateParameter = enddate != null ?
                new ObjectParameter("enddate", enddate) :
                new ObjectParameter("enddate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_assignmodule", modidParameter, teamidParameter, startdateParameter, prjidParameter, enddateParameter);
        }
    
        public virtual ObjectResult<sp_vw_moduleid_team_Result> sp_vw_moduleid_team(Nullable<int> leaderid)
        {
            var leaderidParameter = leaderid.HasValue ?
                new ObjectParameter("leaderid", leaderid) :
                new ObjectParameter("leaderid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vw_moduleid_team_Result>("sp_vw_moduleid_team", leaderidParameter);
        }
    
        public virtual ObjectResult<sp_vw_division_id_module_Result> sp_vw_division_id_module(Nullable<int> modid)
        {
            var modidParameter = modid.HasValue ?
                new ObjectParameter("modid", modid) :
                new ObjectParameter("modid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vw_division_id_module_Result>("sp_vw_division_id_module", modidParameter);
        }
    
        public virtual ObjectResult<sp_vw_emp_request_tl_req_Result> sp_vw_emp_request_tl_req(Nullable<int> tlid)
        {
            var tlidParameter = tlid.HasValue ?
                new ObjectParameter("tlid", tlid) :
                new ObjectParameter("tlid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vw_emp_request_tl_req_Result>("sp_vw_emp_request_tl_req", tlidParameter);
        }
    
        public virtual ObjectResult<sp_reject_list_Result> sp_reject_list(Nullable<int> logid)
        {
            var logidParameter = logid.HasValue ?
                new ObjectParameter("logid", logid) :
                new ObjectParameter("logid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_reject_list_Result>("sp_reject_list", logidParameter);
        }
    
        public virtual ObjectResult<sp_vw_incentive_employee_Result> sp_vw_incentive_employee(Nullable<int> logid)
        {
            var logidParameter = logid.HasValue ?
                new ObjectParameter("logid", logid) :
                new ObjectParameter("logid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vw_incentive_employee_Result>("sp_vw_incentive_employee", logidParameter);
        }
    
        public virtual ObjectResult<sp_vw_incentive_Tl_Result> sp_vw_incentive_Tl(Nullable<int> logid)
        {
            var logidParameter = logid.HasValue ?
                new ObjectParameter("logid", logid) :
                new ObjectParameter("logid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vw_incentive_Tl_Result>("sp_vw_incentive_Tl", logidParameter);
        }
    
        public virtual ObjectResult<Nullable<double>> sp_incentive(Nullable<int> empid, Nullable<int> divid)
        {
            var empidParameter = empid.HasValue ?
                new ObjectParameter("empid", empid) :
                new ObjectParameter("empid", typeof(int));
    
            var dividParameter = divid.HasValue ?
                new ObjectParameter("divid", divid) :
                new ObjectParameter("divid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("sp_incentive", empidParameter, dividParameter);
        }
    
        public virtual ObjectResult<spvwstatusadmin_Result> spvwstatusadmin()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spvwstatusadmin_Result>("spvwstatusadmin");
        }
    
        public virtual ObjectResult<sp_vw_prj_complete_admin_Result> sp_vw_prj_complete_admin()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vw_prj_complete_admin_Result>("sp_vw_prj_complete_admin");
        }
    
        public virtual int sp_update_analyst_submit(Nullable<int> proid)
        {
            var proidParameter = proid.HasValue ?
                new ObjectParameter("proid", proid) :
                new ObjectParameter("proid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_update_analyst_submit", proidParameter);
        }
    
        public virtual ObjectResult<sp_vw_module_team_Result> sp_vw_module_team(Nullable<int> leaderid)
        {
            var leaderidParameter = leaderid.HasValue ?
                new ObjectParameter("leaderid", leaderid) :
                new ObjectParameter("leaderid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vw_module_team_Result>("sp_vw_module_team", leaderidParameter);
        }
    
        public virtual ObjectResult<sp_Admin_Approve_Result> sp_Admin_Approve(Nullable<int> proid)
        {
            var proidParameter = proid.HasValue ?
                new ObjectParameter("proid", proid) :
                new ObjectParameter("proid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Admin_Approve_Result>("sp_Admin_Approve", proidParameter);
        }
    }
}
