//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_team
    {
        public int teamid { get; set; }
        public string teamname { get; set; }
        public int status { get; set; }
        public int leader_id { get; set; }
        public Nullable<bool> isdeleted { get; set; }
    }
}
