//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    
    public partial class sp_view_thread
    {
        public int msg_id { get; set; }
        public string message { get; set; }
        public string name { get; set; }
    }
}
