//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_analystallot
    {
        public int anallotid { get; set; }
        public int analystid { get; set; }
        public int projid { get; set; }
        public int status { get; set; }
        public Nullable<bool> isdeleted { get; set; }
        public Nullable<bool> completed { get; set; }
    }
}
