//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_emprequest
    {
        public int emp_reqid { get; set; }
        public Nullable<int> modid { get; set; }
        public Nullable<int> divid { get; set; }
        public Nullable<int> empid { get; set; }
        public Nullable<int> teamid { get; set; }
        public Nullable<int> daysneeded { get; set; }
        public string eenddate { get; set; }
        public string reason { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<bool> isdeleted { get; set; }
        public Nullable<bool> completed { get; set; }
    }
}
