//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_module
    {
        public int moduleid { get; set; }
        public Nullable<int> prjid { get; set; }
        public string modulename { get; set; }
        public string description { get; set; }
        public string info { get; set; }
        public string document_data { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<bool> isdeleted { get; set; }
        public Nullable<bool> completed { get; set; }
        public Nullable<bool> split { get; set; }
    }
}
