//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_moddiv
    {
        public int moddivid { get; set; }
        public Nullable<int> modid { get; set; }
        public string divname { get; set; }
        public string description { get; set; }
        public string documents { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<bool> isdeleted { get; set; }
        public Nullable<bool> completed { get; set; }
    }
}
